version: '3.9'

services:
  seasonpackarr:
    container_name: seasonpackarr
    image: ghcr.io/nuxencs/seasonpackarr:develop
    user: ${PUID}:${PGID} #UID and GID
    volumes:
      - ${DOCKERCONFDIR}/seasonpackarr:/config # location of the config file
      - /data/torrents/tv-hd:/data/torrents/tv-hd # these need to be the path you want your season packs to sit at
