version: '3.9'

  services:
    seasonpackarr:
      container_name: seasonpackarr
      image: ghcr.io/nuxencs/seasonpackarr:develop
      user: ${PUID}:${PGID} #UID and GID 
      volumes:
        - ${DOCKERCONFDIR}/seasonpackarr:/config #location of the config file
        - ${DOCKERDATADIR}/torrents/cross-seeds:/preimportpath #PreImportPath can be /preimportpath or whatever, just needs to fit in the config file with your mapping here.
